### ISSUE TITLE
Unable to build on ios node_modules/react-native-multithreading/cpp/RNMultithreadingInstaller.h:10:10: fatal error: 'Scheduler.h' file       not found

### ISSUE THREAD

**Issue by acollazomayer** [mrousavy/react-native-multithreading#38]
I am not able to build my app.

node_modules/react-native-multithreading/cpp/RNMultithreadingInstaller.h:10:10: fatal error: 'Scheduler.h' file  not found

This is the error that xcode prints.

**Comment by joshua-davis-rose** [comment]
+1

**Comment by TheFe91** [comment]
+1

**Comment by lockieluke** [comment]
is this library dead

**Comment by mrousavy** [comment]
it is not dead. As stated in the readme, this project is a proof of concept. Unlike all of my other libraries (VisionCamera, Blurhash, MMKV, pipestate, ...), Multithreading is not used in production by any of my apps - that's why I am not keeping it up to date.
It perfectly works here as demonstrated in the example app I also built specifically for this, but to make it work for more recent RN versions you probably need to fix some CMake/build.grade build steps.

**Comment by mfbx9da4** [comment]
@mrousavy this is an ios issue why would updating build.gradle fix anything?

**Comment by mrousavy** [comment]
Then fix the Podfile 🤷

**Comment by mfbx9da4** [comment]
okay I'll try and look into this!
