### ISSUE TITLE
App crashes immediately ("libjsc.so" not found)

### ISSUE THREAD

**Issue by DominickVale** [mrousavy/react-native-multithreading#45]
These are the errors i found in flipper:
```
java.lang.UnsatisfiedLinkError: dlopen failed: library "libjsc.so" not found
```
```
FATAL EXCEPTION: create_react_context

java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN10reanimated16RuntimeDecorator15decorateRuntimeERN8facebook3jsi7RuntimeENSt6__ndk112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE" referenced by "/data/app/com.dominickv.ambientify-lEsnb2qmuVnrWOCeH3WqEg==/lib/x86/librnmultithreading.so"...

FATAL EXCEPTION: create_react_context
Process: com.dominickv.ambientify, PID: 7022
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN10reanimated16RuntimeDecorator15decorateRuntimeERN8facebook3jsi7RuntimeENSt6__ndk112basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEE" referenced by "/data/app/com.dominickv.ambientify-lEsnb2qmuVnrWOCeH3WqEg==/lib/x86/librnmultithreading.so"...
	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
	at java.lang.System.loadLibrary(System.java:1657)
	at com.reactnativemultithreading.MultithreadingModule.<clinit>(MultithreadingModule.java:26)
	at com.reactnativemultithreading.MultithreadingPackage.createNativeModules(MultithreadingPackage.java:17)
	at com.facebook.react.ReactPackageHelper.getNativeModuleIterator(ReactPackageHelper.java:42)
	at com.facebook.react.NativeModuleRegistryBuilder.processPackage(NativeModuleRegistryBuilder.java:42)
	at com.facebook.react.ReactInstanceManager.processPackage(ReactInstanceManager.java:1425)
	at com.facebook.react.ReactInstanceManager.processPackages(ReactInstanceManager.java:1396)
	at com.facebook.react.ReactInstanceManager.createReactContext(ReactInstanceManager.java:1287)
	at com.facebook.react.ReactInstanceManager.access$1100(ReactInstanceManager.java:136)
	at com.facebook.react.ReactInstanceManager$5.run(ReactInstanceManager.java:1065)
	at java.lang.Thread.run(Thread.java:764)
```
I followed all the setup instructions, even the ones that aren't in the readme (i found it in other issues)... I'm using hermes. RN-0.66, rn-reanimated 2.3.0.

**Comment by ALexandreM75013** [comment]
Exact same issues. I have just added react-native-multithreading today.

**Comment by DominickVale** [comment]
I've been trying to set this up for more than one day. I'm trying to gather up all the required steps from all the issues but it doesn't help. Fixed one thing breaks something else. 1/10 on the setup documentation...

**Comment by mrousavy** [comment]
> I've been trying to set this up for more than one day. I'm trying to gather up all the required steps from all the issues but it doesn't help. (I even tried installing the additional mmkv library which i have no use for)... Fixed one thing breaks something else. 1/10 on the setup documentation...
> 
> Edit: after wasting another day trying every possible combination of solutions in the issues and noticing several people having the same problem last year I'm going to give up and assume this library is kind of unmaintained (last actual non-readme related commit was 9 months ago)


@DominickVale Looks like you are not capable of reading the documentation, because literally the first line of content in the README (<-- this means "_read me_") says that this library is a **proof of concept** and you **shouldn't use it in production**. 

![Screenshot 2022-02-02 at 14 52 28](https://user-images.githubusercontent.com/15199031/152166855-b94ec89d-3691-4ba3-b552-3ff770dbdf1f.png)

I am not sure how I can make this more clear except than flying to your house and telling you in person.

You can run the `example/` app here which I built specifically for people to take a look at the concept and try it for themselves, which works great for me, on my machine. 

---

Instead of talking bad about other people's work, how about you build it for yourself? It took me a long time figuring out how Reanimated works, and I had to write a few lines of C++ code and merge them to their upstream repository to finally experiment with multithreading in JavaScript / React Native. I think my part is documented pretty good, it explains all pros and cons, explains how it works, etc. etc.

**Comment by DominickVale** [comment]
I wasn't "talking bad" about the library per se, i was referring only to the documentation regarding setting it up, since some important stuff is only found in the issues. If i thought the library was bad i would've just said 1/10 library sucks. But alright, i had all my hopes in this library but i guess that's what i get by hoping that you can really do anything with react-native... Sorry if i sounded rude to you.

**Comment by mrousavy** [comment]
No, it is a proof of concept library. My other libraries (VisionCamera, MMKV, etc.) are used in production, but this one isn't. That's also why the setup instructions aren't detailed and not tested.
